version: '3'
services:

  frontend:
    #image: architsagar/frontend_docker:latest
    image: frontend_docker
    # image : ashwink07/frontend_docker_v1:latest
    ports:
      - "5000:80"
    depends_on:
      - backend
    expose:
      - 5000
    container_name: frontend

  database:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: unbxd
      POSTGRES_PORT: 5432
      POSTGRES_HOST_AUTH_METHOD: trust
    container_name: database

  backend:
    #image: architsagar/backend_docker:latest
    image: backend_docker
    # image: ashwink07/backend_docker_v2:latest
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - redis
      - database
    expose:
      - 3000
    container_name: backend

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    environment:
      REDIS_HOSTNAME: redis
    volumes:
      - ./config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
    container_name: redis

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080
